cieutils: modules.benchutils.Result.SystemInfo Class Reference
modules.benchutils.Result.SystemInfo Class Reference
A dict restricted to "OS", "hardware", and "python".
Public Member Functions
__init__ (self, dict inputMap={})
Reconstruct a SystemInfo instance from a dict or initialize one with the current system's info.
dict serialize (self)
list[str] keys (self)
bool __contains__ (self, str item)
dict __getitem__ (self, str key)
Static Public Member Functions
"SystemInfo" deserialize (dict map)
Detailed Description
A dict restricted to "OS", "hardware", and "python".
Constructor & Destructor Documentation
__init__()
modules.benchutils.Result.SystemInfo.__init__ (self, dict inputMap = {})
Reconstruct a SystemInfo instance from a dict or initialize one with the current system's info.
Only "OS", "hardware", and "python" are copied from inputDict and the rest of the entries are ignored. Missing entries are added using the current system's info. The internal dict has the following structure:
{
       "OS" : {
           "system" : "",
           "release" : "",
           "version" : ""
       },
       "hardware" : {
           "machine" : "",
           "processor" : "",
           "memory" : ""
       },
       "python" : {
           "build" : "",
           "compiler" : "",
           "version" : ""
       }
    }
Note
Fetching the size of the system's main memory requires the 'psutil' package.
Properties that could not be fetched are replaced by "unavailable".
References modules.benchutils.Result.SystemInfo.__getHardware(), modules.benchutils.Result.SystemInfo.__getOS(), modules.benchutils.Result.SystemInfo.__getPython(), and modules.benchutils.Result.SystemInfo.__map.
Member Function Documentation
__contains__()
bool modules.benchutils.Result.SystemInfo.__contains__ (self, str item)
References modules.benchutils.Result.SystemInfo.__map.
__getitem__()
dict modules.benchutils.Result.SystemInfo.__getitem__ (self, str key)
References modules.benchutils.Result.SystemInfo.__map.
deserialize()
"SystemInfo" modules.benchutils.Result.SystemInfo.deserialize (dict map) static
keys()
list[str] modules.benchutils.Result.SystemInfo.keys (self)
References modules.benchutils.Result.SystemInfo.__map, and modules.benchutils.Result.SystemInfo.keys().
Referenced by modules.benchutils.Result.Result.hasKey(), and modules.benchutils.Result.SystemInfo.keys().
serialize()
dict modules.benchutils.Result.SystemInfo.serialize (self)
References modules.benchutils.Result.SystemInfo.__map.
Referenced by modules.benchutils.Result.Result.Case.Quantity.__str__().
The documentation for this class was generated from the following file:
Result.py