cieutils: cie::OptionalRef< TElement > Class Template Reference
cie::OptionalRef< TElement > Class Template Reference
Utility Library
An optional, modeling a pointer.
#include <OptionalRef.hpp>
Public Types
using value_type = TElement &
Public Member Functions
OptionalRef () noexcept
Construct an invalid (uninitialized) optional.
OptionalRef (TElement &rElement) noexcept
Construct an optional reference to the provided instance.
OptionalRef (OptionalRef &&rRhs) noexcept=default
OptionalRef (const OptionalRef &rRhs) noexcept=default
OptionalRef & operator= (OptionalRef &&rRhs) noexcept=default
OptionalRef & operator= (const OptionalRef &rRhs) noexcept=default
OptionalRef & operator= (TElement &rElement) noexcept
Assign the provided instance to the optional.
bool has_value () const noexcept
Check whether the optional is valid.
operator bool () const noexcept
Check whether the optional is valid.
TElement & value () const
Access the stored reference.
TElement & operator* () const noexcept
Access the stored reference.
void reset () noexcept
Clear the optional.
operator OptionalRef< const TElement > () noexcept
Cast to constant reference.
Detailed Description
template<class TElement>
class cie::OptionalRef< TElement >
An optional, modeling a pointer.
OptionalRef stores a pointer to the instance it was assigned and stores the value indicator in the least significant bit of the pointer. As a result, the memory alignment of OptionalRef is identical to that of the stored pointer.
Member Typedef Documentation
value_type
template<class TElement > using cie::OptionalRef< TElement >::value_type = TElement&
Constructor & Destructor Documentation
OptionalRef() [1/4]
template<class TElement > cie::OptionalRef< TElement >::OptionalRef () inline noexcept
Construct an invalid (uninitialized) optional.
OptionalRef() [2/4]
template<class TElement > cie::OptionalRef< TElement >::OptionalRef (TElement & rElement) inline noexcept
Construct an optional reference to the provided instance.
OptionalRef() [3/4]
template<class TElement > cie::OptionalRef< TElement >::OptionalRef (OptionalRef< TElement > && rRhs) default noexcept
OptionalRef() [4/4]
template<class TElement > cie::OptionalRef< TElement >::OptionalRef (const OptionalRef< TElement > & rRhs) default noexcept
Member Function Documentation
has_value()
template<class TElement > bool cie::OptionalRef< TElement >::has_value () const inline noexcept
Check whether the optional is valid.
Referenced by cie::OptionalRef< TElement >::operator bool(), cie::OptionalRef< TElement >::operator OptionalRef< const TElement >(), and cie::OptionalRef< TElement >::value().
operator bool()
template<class TElement > cie::OptionalRef< TElement >::operator bool () const inline explicit noexcept
Check whether the optional is valid.
References cie::OptionalRef< TElement >::has_value().
operator OptionalRef< const TElement >()
template<class TElement > cie::OptionalRef< TElement >::operator OptionalRef< const TElement > () inline noexcept
Cast to constant reference.
References cie::OptionalRef< TElement >::has_value(), and cie::OptionalRef< TElement >::value().
operator*()
template<class TElement > TElement & cie::OptionalRef< TElement >::operator* () const inline noexcept
Access the stored reference.
Exceptions
if the optional is uninitialized.
References cie::OptionalRef< TElement >::value().
operator=() [1/3]
template<class TElement > OptionalRef & cie::OptionalRef< TElement >::operator= (const OptionalRef< TElement > & rRhs) default noexcept
operator=() [2/3]
template<class TElement > OptionalRef & cie::OptionalRef< TElement >::operator= (OptionalRef< TElement > && rRhs) default noexcept
operator=() [3/3]
template<class TElement > OptionalRef & cie::OptionalRef< TElement >::operator= (TElement & rElement) inline noexcept
Assign the provided instance to the optional.
reset()
template<class TElement > void cie::OptionalRef< TElement >::reset () inline noexcept
Clear the optional.
value()
template<class TElement > TElement & cie::OptionalRef< TElement >::value () const inline
Access the stored reference.
Exceptions
if the optional is uninitialized.
References CIE_THROW, and cie::OptionalRef< TElement >::has_value().
Referenced by cie::OptionalRef< TElement >::operator OptionalRef< const TElement >(), and cie::OptionalRef< TElement >::operator*().
Member Data Documentation
integer
template<class TElement > PointerInteger cie::OptionalRef< TElement >::integer
pointer
template<class TElement > TElement* cie::OptionalRef< TElement >::pointer
The documentation for this class was generated from the following file:
OptionalRef.hpp