cieutils: cie::STLContainerBase< TBase > Class Template Reference
cie::STLContainerBase< TBase > Class Template Reference
Utility Library
#include <STLContainerBase.hpp>
Public Member Functions
Constructor / Destructor
STLContainerBase (const std::initializer_list< value_type > &rInitializer)
STLContainerBase (const std::initializer_list< value_type > &rInitializer)
STLContainerBase (RightRef< TBase > r_rhs) noexcept
STLContainerBase (Ref< const TBase > r_rhs)
STLContainerBase (STLContainerBase< TBase > &&r_rhs) noexcept=default
STLContainerBase (const STLContainerBase< TBase > &r_rhs)=default
template<class ... TArgs>
STLContainerBase (TArgs &&... rArgs)
STLContainerBase< TBase > & operator= (STLContainerBase< TBase > &&r_rhs) noexcept=default
STLContainerBase< TBase > & operator= (const STLContainerBase< TBase > &r_rhs) noexcept=default
virtual ~STLContainerBase ()
Common members
size_type size () const noexcept
bool empty () const noexcept
iterator begin () noexcept
const_iterator begin () const noexcept
const_iterator cbegin () const noexcept
reverse_iterator rbegin () noexcept
const_reverse_iterator rbegin () const noexcept
const_reverse_iterator crbegin () const noexcept
iterator end () noexcept
const_iterator end () const noexcept
const_iterator cend () const noexcept
reverse_iterator rend () noexcept
const_reverse_iterator rend () const noexcept
const_reverse_iterator crend () const noexcept
Optional members
reference at (size_type index) noexcept
const_reference at (size_type index) const noexcept
reference operator[] (size_type index) noexcept
const_reference operator[] (size_type index) const noexcept
pointer data () noexcept
const_pointer data () const noexcept
reference front () noexcept
const_reference front () const noexcept
reference back () noexcept
const_reference back () const noexcept
void reserve (size_type capacity)
auto capacity () const noexcept
void clear ()
iterator erase (iterator position)
iterator erase (iterator begin, iterator end)
void push_front (const value_type &rValue)
void push_front (value_type &&rValue)
void push_back (const value_type &rValue)
void push_back (value_type &&rValue)
template<class ... TArgs>
requires concepts::detail::HasEmplaceBack<TBase, TArgs...>
reference emplace_front (TArgs &&... rArgs)
template<class ... TArgs>
requires concepts::detail::HasEmplaceBack<TBase, TArgs...>
reference emplace_back (TArgs &&... rArgs)
template<class ... TArgs>
requires concepts::detail::HasInsert<TBase, TArgs...>
void insert (TArgs &&... rArgs)
void pop_front ()
void pop_back ()
void resize (size_type size)
Friends
bool operator< (const STLContainerBase &r_lhs, const STLContainerBase &r_rhs)
bool operator!= (const STLContainerBase &r_lhs, const STLContainerBase &r_rhs)
Constructor & Destructor Documentation
STLContainerBase() [1/7]
template<concepts::Container TBase> cie::STLContainerBase< TBase >::STLContainerBase (const std::initializer_list< value_type > & rInitializer) inline
References cie::STLContainerBase< TBase >::begin(), CIE_BEGIN_EXCEPTION_TRACING, CIE_END_EXCEPTION_TRACING, cie::STLContainerBase< TBase >::end(), cie::utils::reserve(), and cie::STLContainerBase< TBase >::size().
STLContainerBase() [2/7]
template<concepts::Container TBase> cie::STLContainerBase< TBase >::STLContainerBase (const std::initializer_list< value_type > & rInitializer) inline
References cie::STLContainerBase< TBase >::begin(), CIE_BEGIN_EXCEPTION_TRACING, CIE_END_EXCEPTION_TRACING, cie::STLContainerBase< TBase >::end(), cie::utils::resize(), and cie::STLContainerBase< TBase >::size().
STLContainerBase() [3/7]
template<concepts::Container TBase> cie::STLContainerBase< TBase >::STLContainerBase (RightRef< TBase > r_rhs) inline noexcept
STLContainerBase() [4/7]
template<concepts::Container TBase> cie::STLContainerBase< TBase >::STLContainerBase (Ref< const TBase > r_rhs) inline
STLContainerBase() [5/7]
template<concepts::Container TBase> cie::STLContainerBase< TBase >::STLContainerBase (STLContainerBase< TBase > && r_rhs) default noexcept
STLContainerBase() [6/7]
template<concepts::Container TBase> cie::STLContainerBase< TBase >::STLContainerBase (const STLContainerBase< TBase > & r_rhs) default
STLContainerBase() [7/7]
template<concepts::Container TBase> template<class ... TArgs> cie::STLContainerBase< TBase >::STLContainerBase (TArgs &&... rArgs) inline
~STLContainerBase()
template<concepts::Container TBase> virtual cie::STLContainerBase< TBase >::~STLContainerBase () inline virtual
Member Function Documentation
at() [1/2]
template<concepts::Container TBase> const_reference cie::STLContainerBase< TBase >::at (size_type index) const inline noexcept
at() [2/2]
template<concepts::Container TBase> reference cie::STLContainerBase< TBase >::at (size_type index) inline noexcept
back() [1/2]
template<concepts::Container TBase> const_reference cie::STLContainerBase< TBase >::back () const inline noexcept
back() [2/2]
template<concepts::Container TBase> reference cie::STLContainerBase< TBase >::back () inline noexcept
begin() [1/2]
template<concepts::Container TBase> const_iterator cie::STLContainerBase< TBase >::begin () const inline noexcept
begin() [2/2]
template<concepts::Container TBase> iterator cie::STLContainerBase< TBase >::begin () inline noexcept
Referenced by cie::STLContainerBase< TBase >::erase(), and cie::STLContainerBase< TBase >::STLContainerBase().
capacity()
template<concepts::Container TBase> auto cie::STLContainerBase< TBase >::capacity () const inline noexcept
Referenced by cie::STLContainerBase< TBase >::reserve().
cbegin()
template<concepts::Container TBase> const_iterator cie::STLContainerBase< TBase >::cbegin () const inline noexcept
cend()
template<concepts::Container TBase> const_iterator cie::STLContainerBase< TBase >::cend () const inline noexcept
clear()
template<concepts::Container TBase> void cie::STLContainerBase< TBase >::clear () inline
crbegin()
template<concepts::Container TBase> const_reverse_iterator cie::STLContainerBase< TBase >::crbegin () const inline noexcept
crend()
template<concepts::Container TBase> const_reverse_iterator cie::STLContainerBase< TBase >::crend () const inline noexcept
data() [1/2]
template<concepts::Container TBase> const_pointer cie::STLContainerBase< TBase >::data () const inline noexcept
data() [2/2]
template<concepts::Container TBase> pointer cie::STLContainerBase< TBase >::data () inline noexcept
emplace_back()
template<concepts::Container TBase> template<class ... TArgs> requires concepts::detail::HasEmplaceBack<TBase, TArgs...> reference cie::STLContainerBase< TBase >::emplace_back (TArgs &&... rArgs) inline
emplace_front()
template<concepts::Container TBase> template<class ... TArgs> requires concepts::detail::HasEmplaceBack<TBase, TArgs...> reference cie::STLContainerBase< TBase >::emplace_front (TArgs &&... rArgs) inline
empty()
template<concepts::Container TBase> bool cie::STLContainerBase< TBase >::empty () const inline noexcept
end() [1/2]
template<concepts::Container TBase> const_iterator cie::STLContainerBase< TBase >::end () const inline noexcept
end() [2/2]
template<concepts::Container TBase> iterator cie::STLContainerBase< TBase >::end () inline noexcept
Referenced by cie::STLContainerBase< TBase >::erase(), and cie::STLContainerBase< TBase >::STLContainerBase().
erase() [1/2]
template<concepts::Container TBase> iterator cie::STLContainerBase< TBase >::erase (iterator begin, iterator end) inline
References cie::STLContainerBase< TBase >::begin(), and cie::STLContainerBase< TBase >::end().
erase() [2/2]
template<concepts::Container TBase> iterator cie::STLContainerBase< TBase >::erase (iterator position) inline
front() [1/2]
template<concepts::Container TBase> const_reference cie::STLContainerBase< TBase >::front () const inline noexcept
front() [2/2]
template<concepts::Container TBase> reference cie::STLContainerBase< TBase >::front () inline noexcept
insert()
template<concepts::Container TBase> template<class ... TArgs> requires concepts::detail::HasInsert<TBase, TArgs...> void cie::STLContainerBase< TBase >::insert (TArgs &&... rArgs) inline
operator=() [1/2]
template<concepts::Container TBase> STLContainerBase< TBase > & cie::STLContainerBase< TBase >::operator= (const STLContainerBase< TBase > & r_rhs) default noexcept
operator=() [2/2]
template<concepts::Container TBase> STLContainerBase< TBase > & cie::STLContainerBase< TBase >::operator= (STLContainerBase< TBase > && r_rhs) default noexcept
operator[]() [1/2]
template<concepts::Container TBase> const_reference cie::STLContainerBase< TBase >::operator[] (size_type index) const inline noexcept
operator[]() [2/2]
template<concepts::Container TBase> reference cie::STLContainerBase< TBase >::operator[] (size_type index) inline noexcept
pop_back()
template<concepts::Container TBase> void cie::STLContainerBase< TBase >::pop_back () inline
pop_front()
template<concepts::Container TBase> void cie::STLContainerBase< TBase >::pop_front () inline
push_back() [1/2]
template<concepts::Container TBase> void cie::STLContainerBase< TBase >::push_back (const value_type & rValue) inline
push_back() [2/2]
template<concepts::Container TBase> void cie::STLContainerBase< TBase >::push_back (value_type && rValue) inline
push_front() [1/2]
template<concepts::Container TBase> void cie::STLContainerBase< TBase >::push_front (const value_type & rValue) inline
push_front() [2/2]
template<concepts::Container TBase> void cie::STLContainerBase< TBase >::push_front (value_type && rValue) inline
rbegin() [1/2]
template<concepts::Container TBase> const_reverse_iterator cie::STLContainerBase< TBase >::rbegin () const inline noexcept
rbegin() [2/2]
template<concepts::Container TBase> reverse_iterator cie::STLContainerBase< TBase >::rbegin () inline noexcept
Referenced by cie::makeContiguousStrides().
rend() [1/2]
template<concepts::Container TBase> const_reverse_iterator cie::STLContainerBase< TBase >::rend () const inline noexcept
rend() [2/2]
template<concepts::Container TBase> reverse_iterator cie::STLContainerBase< TBase >::rend () inline noexcept
Referenced by cie::makeContiguousStrides().
reserve()
template<concepts::Container TBase> void cie::STLContainerBase< TBase >::reserve (size_type capacity) inline
References cie::STLContainerBase< TBase >::capacity().
Referenced by cie::utils::reserve().
resize()
template<concepts::Container TBase> void cie::STLContainerBase< TBase >::resize (size_type size) inline
References cie::STLContainerBase< TBase >::size().
Referenced by cie::utils::resize().
size()
template<concepts::Container TBase> size_type cie::STLContainerBase< TBase >::size () const inline noexcept
Referenced by cie::STLContainerBase< TBase >::resize(), and cie::STLContainerBase< TBase >::STLContainerBase().
Friends And Related Symbol Documentation
operator!=
template<concepts::Container TBase> bool operator!= (const STLContainerBase< TBase > & r_lhs, const STLContainerBase< TBase > & r_rhs) friend
operator<
template<concepts::Container TBase> bool operator< (const STLContainerBase< TBase > & r_lhs, const STLContainerBase< TBase > & r_rhs) friend
The documentation for this class was generated from the following file:
STLContainerBase.hpp