cieutils: cie::io::Serializer< TTag > Class Template Reference
cie::io::Serializer< TTag > Class Template Reference
Utility Library
#include <Serializer.hpp>
Public Types
using SerializerStream = Traits::SerializerStream
using DeserializerStream = Traits::DeserializerStream
Static Public Member Functions
template<concepts::TriviallySerializable T>
static void serialize (Ref< SerializerStream > r_stream, T object)
template<concepts::NonTriviallySerializable T>
static void serialize (Ref< SerializerStream > r_stream, Ref< const T > r_object)
template<class T >
requires concepts::Serializable<T,TTag>
static void serialize (Ref< SerializerStream > r_stream, Ptr< const T > begin, Size numberOfItems)
template<concepts::Deserializable T>
static void deserialize (Ref< DeserializerStream > r_stream, Ref< T > r_output)
template<concepts::Deserializable< TTag > T>
static void deserialize (Ref< DeserializerStream > r_stream, Ptr< T > begin, Size numberOfItems)
Member Typedef Documentation
DeserializerStream
template<concepts::AnyOf< tags::Binary, tags::Text > TTag> using cie::io::Serializer< TTag >::DeserializerStream = Traits::DeserializerStream
SerializerStream
template<concepts::AnyOf< tags::Binary, tags::Text > TTag> using cie::io::Serializer< TTag >::SerializerStream = Traits::SerializerStream
Member Function Documentation
deserialize() [1/2]
template<concepts::AnyOf< tags::Binary, tags::Text > TTag> template<concepts::Deserializable< TTag > T> static void cie::io::Serializer< TTag >::deserialize (Ref< DeserializerStream > r_stream, Ptr< T > begin, Size numberOfItems) inline static
References CIE_CHECK.
deserialize() [2/2]
template<concepts::AnyOf< tags::Binary, tags::Text > TTag> template<concepts::Deserializable T> static void cie::io::Serializer< TTag >::deserialize (Ref< DeserializerStream > r_stream, Ref< T > r_output) inline static
References CIE_CHECK.
serialize() [1/3]
template<concepts::AnyOf< tags::Binary, tags::Text > TTag> template<class T > requires concepts::Serializable<T,TTag> static void cie::io::Serializer< TTag >::serialize (Ref< SerializerStream > r_stream, Ptr< const T > begin, Size numberOfItems) inline static
References CIE_CHECK, and cie::io::Serializer< TTag >::serialize().
Referenced by modules.benchutils.Result.Result.Case.Quantity::__str__().
serialize() [2/3]
template<concepts::AnyOf< tags::Binary, tags::Text > TTag> template<concepts::NonTriviallySerializable T> static void cie::io::Serializer< TTag >::serialize (Ref< SerializerStream > r_stream, Ref< const T > r_object) inline static
References CIE_CHECK.
Referenced by modules.benchutils.Result.Result.Case.Quantity::__str__().
serialize() [3/3]
template<concepts::AnyOf< tags::Binary, tags::Text > TTag> template<concepts::TriviallySerializable T> static void cie::io::Serializer< TTag >::serialize (Ref< SerializerStream > r_stream, T object) inline static
References CIE_CHECK.
Referenced by modules.benchutils.Result.Result.Case.Quantity::__str__(), and cie::io::Serializer< TTag >::serialize().
The documentation for this class was generated from the following file:
Serializer.hpp