cieutils: Utility Library
Utility Library
Concepts
concept cie::concepts::ThreadPool
concept cie::concepts::CIEException
concept cie::concepts::STLException
concept cie::concepts::TriviallySerializable
Concept for trivially serializable types.
concept cie::concepts::BinarySerializable
concept cie::concepts::TextSerializable
concept cie::concepts::Serializable
concept cie::concepts::NonTriviallySerializable
concept cie::concepts::TriviallyDeserializable
Concept for trivially deserializable types.
concept cie::concepts::BinaryDeserializable
concept cie::concepts::TextDeserializable
concept cie::concepts::Deserializable
concept cie::concepts::NonTriviallyDeserializable
concept cie::concepts::ContiguousTreeNode
Classes
class cie::utils::ArgParse
class cie::ct::ArgumentMapper< TDefaults >
class cie::ct::Match< Ts >
Compare two parameter packs.
class cie::ct::MatchTuple< T >
Compare the parameter packs of two tuples.
class cie::ct::MatchTuple< std::tuple< Ts... > >
Compare the parameter packs of two tuples.
class cie::ct::Filter< TSet, TExcept >
class cie::ct::Filter< std::tuple< TSet... >, std::tuple< TExcept... > >
class cie::ct::Range< Ts >
class cie::ct::Select< Ts >
class cie::ct::Select<>
struct cie::ct::Signed
struct cie::ct::Unsigned
class cie::mp::Mutex< TTag >
class cie::mp::Mutex< tags::SMP >
class cie::mp::Mutex< tags::Serial >
class cie::mp::ParallelFor< TIndex, TStorage >
Parallel for construct with thread local storage.
class cie::mpi::RankID
class cie::mp::ResourceLoader< TResource >
class cie::mp::ResourceQueue< TResource >
class cie::mp::ThreadLocal< TStored >
class cie::mp::ThreadPool< TStorage >
class cie::mp::ThreadPoolBase
class cie::mp::ThreadPoolStorage< TStorage >
class cie::mp::ThreadStorage< TArgs >
class cie::Exception
struct cie::NullPtrException
struct cie::AbstractCallException
struct cie::NotImplementedException
struct cie::OutOfRangeException
struct cie::DivisionByZeroException
struct cie::GeometryException
struct cie::MemoryException
class cie::io::JSONObject
Basic interface for a json parser.
struct cie::utils::io::MatrixMarket
IO class for reading and writing matrices in MatrixMarket format.
class cie::io::Serializer< TTag >
struct cie::io::Traits
class cie::utils::LogBlock
class cie::utils::Logger
class cie::utils::LoggerSingleton
class cie::OutputStream
class cie::utils::Profiler< TTimeUnit >
class cie::StreamInterceptor
struct cie::utils::IntegerComparison< TInteger >
class cie::utils::FloatComparison< TFloat >
class cie::utils::Comparison< T >
class cie::utils::Comparison< TFloat >
class cie::utils::Comparison< TContainer >
class cie::utils::EqualityComparison< T >
class cie::utils::Ordering< T >
class cie::utils::NChooseK
class cie::utils::observer::Observer
class cie::utils::observer::Subject
class cie::utils::FileManager
class cie::utils::TransformIterator< TIterator, TTransform >
class cie::utils::TransformView< ContainerType, OutputType >
class cie::utils::UnstructuredView< TValue, TContainer >
A container that stores pointers to items but provides access through references.
struct cie::FunctionTraits< T >
struct cie::FunctionTraits< std::function< TReturn(TArguments...)> >
class cie::utils::MarchingContainer< ValueType >
A container that only holds a specified number of latest values.
class cie::OptionalRef< TElement >
An optional, modeling a pointer.
class cie::utils::StateIterator< IteratorType >
class cie::utils::InternalStateIterator< TContainer >
Helper class for permutations.
struct cie::StaticArrayTraits< T >
struct cie::StaticArrayTraits< StaticArray< T, S > >
struct cie::StaticArrayTraits< std::array< T, S > >
class cie::STLContainerBase< TBase >
class cie::utils::StrongTypeDef< T, Tag >
class cie::utils::ConstructorTracker< Tag >
class cie::utils::AbsTree< TSelf, TContainer, TStored, TArgs >
class cie::utils::ContiguousTree< TNode, TIndex, TParallelTag >
class cie::HierarchicalInteger< Dim, TValue >
class cie::Color
class cie::utils::IDObject< TID >
struct cie::CopyConstQualifier< Source, Target >
struct cie::CopyConstQualifier< Source, Target >
class cie::utils::NamedObject
struct cie::tags::Null
Tag to indicate a void property.
struct cie::tags::Lazy
Tag to indicate lazy execution.
struct cie::tags::Eager
Tag to indicate eager execution.
struct cie::tags::Serial
Tag to indicate a lack of parallelism.
struct cie::tags::SMP
Tag to indicate shared memory parallelism.
struct cie::tags::MPI
Tag to indicate process parallelism.
struct cie::tags::Binary
Tag to indicate binary representation.
struct cie::tags::Text
Tag to indicate text representation.
class cie::NoInitWrapper< T >
Typedefs
template<std::size_t N>
using cie::ct::MakeIndexSequence = std::make_index_sequence< N >
template<std::size_t ... Is>
using cie::ct::IndexSequence = std::index_sequence< Is... >
template<std::size_t N>
using cie::ct::MakeReverseIndexSequence = impl::ReverseIndexSequence< N-1, std::make_index_sequence< N > >
template<std::size_t ... Is>
using cie::ct::ReverseIndexSequence = IndexSequence< Is... >
using cie::io::BinarySerializer = Serializer< tags::Binary >
using cie::io::TextSerializer = Serializer< tags::Text >
template<class TValue , class ... TArgs>
using cie::DynamicArray = STLContainerBase< std::vector< TValue, TArgs... > >
template<class TValue , Size ArraySize>
using cie::StaticArray = STLContainerBase< std::array< TValue, ArraySize > >
Functions
const std::unordered_set< std::thread::id > & cie::mp::getThreadIDs ()
template<concepts::STLException TException>
TException cie::exceptionFactory (const String &r_location, const String &r_message, const String &r_name) noexcept
template<concepts::STLException TException>
TException cie::exceptionFactory (TException &r_exception, const String &r_location, const String &r_additionalMessage) noexcept
std::ostream & cie::io::operator<< (std::ostream &r_stream, const JSONObject &r_json)
template<Size NDigits, concepts::Integer NT>
constexpr void cie::utils::baseN (NT base10, NT base, StaticArray< NT, NDigits > &output)
template<Size NDigits, concepts::Integer NT>
constexpr StaticArray< NT, NDigits > cie::utils::baseN (NT base10, NT base)
template<Size NDigits, concepts::Integer NT>
constexpr NT cie::utils::base10 (const StaticArray< NT, NDigits > &base_N, NT base)
template<Size NDigits, concepts::Integer NT>
constexpr NT cie::utils::reinterpretBase (const StaticArray< NT, NDigits > &base_N, NT newBase)
template<concepts::Integer TInteger, concepts::Integer TIndex = Size>
TInteger cie::utils::flipBit (TInteger integer, TIndex bitIndex)
template<concepts::Integer TInteger, concepts::Integer TIndex = Size>
bool cie::utils::getBit (TInteger integer, TIndex bitIndex)
template<concepts::UnsignedInteger TInteger>
constexpr std::uint8_t cie::utils::getMSBIndex (TInteger integer) noexcept
Get the index of the most significat set bit (counting from LSB)
template<concepts::UnsignedInteger TInteger>
std::uint8_t cie::utils::getNumberOfTrailingZeros (TInteger integer) noexcept
Find the number of trailing zeros of the input integer's binary representation.
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd>
TValue cie::utils::evaluatePolynomialNaive (TValue argument, TItBegin it_begin, const TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd>
TValue cie::utils::evaluatePolynomialHorner (TValue argument, const TItBegin it_begin, TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd>
TValue cie::utils::evaluatePolynomialHornerStabilized (TValue argument, TItBegin it_begin, const TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd>
TValue cie::utils::evaluatePolynomialHornerCompound (TValue argument, TItBegin it_begin, TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
template<concepts::Integer BaseType, concepts::Integer ExponentType>
constexpr BaseType cie::intPow (BaseType base, ExponentType exponent)
template<class TIterator , class TFunction >
auto cie::utils::makeTransformIterator (TIterator it, const TFunction *p_function)
template<class OutputType , class ContainerType >
TransformView< ContainerType, OutputType > cie::utils::makeTransformView (const ContainerType &r_container, typename TransformView< ContainerType, OutputType >::transform_type transformFunctor)
template<class T >
requires concepts::Pointer<T>
std::pointer_traits< typenamestd::decay< T >::type >::element_type & cie::utils::getRef (T &r_p)
template<class T >
requires concepts::Pointer<T>
const std::pointer_traits< typenamestd::decay< T >::type >::element_type & cie::utils::getRef (const T &r_p)
template<class T , class ... Args>
std::shared_ptr< T > cie::utils::make_shared_from_tuple (std::tuple< Args... > &args)
template<concepts::ResizableContainer ContainerType>
void cie::utils::resize (ContainerType &container, Size size)
template<concepts::ReservableContainer ContainerType>
void cie::utils::reserve (ContainerType &container, Size size)
template<class IteratorType >
requires concepts::Container<typename std::iterator_traits<IteratorType>::value_type>
StateIterator< IteratorType > cie::utils::makeStateIterator (IteratorType begin, IteratorType end)
template<concepts::Container ContainerType>
requires concepts::Container<typename ContainerType::value_type>
StateIterator< typename ContainerType::const_iterator > cie::utils::makeStateIterator (const ContainerType &container)
template<concepts::Container ContainerType>
InternalStateIterator< const ContainerType > cie::utils::makeInternalStateIterator (const ContainerType &container, Size size)
template<detail::Zippables ... TContainers>
detail::ZipObject< TContainers... > cie::utils::zip (Size size, TContainers &&... r_containers)
template<detail::Zippables ... TContainers>
detail::ZipObject< TContainers... > cie::utils::zip (TContainers &&... r_containers)
Variables
template<class ... Ts>
constexpr Size cie::ct::PackSize = sizeof...(Ts)
template<class ... Ts>
constexpr bool cie::ct::Empty = PackSize<Ts...> == 0
template<class ... TArgs>
constexpr const bool cie::ct::IsUnique = detail::IsUnique<std::tuple<TArgs...>>::isUnique()
Detailed Description
Typedef Documentation
BinarySerializer
using cie::io::BinarySerializer = typedef Serializer<tags::Binary>
DynamicArray
template<class TValue , class ... TArgs> using cie::DynamicArray = typedef STLContainerBase<std::vector<TValue,TArgs...> >
IndexSequence
template<std::size_t ... Is> using cie::ct::IndexSequence = typedef std::index_sequence<Is...>
MakeIndexSequence
template<std::size_t N> using cie::ct::MakeIndexSequence = typedef std::make_index_sequence<N>
MakeReverseIndexSequence
template<std::size_t N> using cie::ct::MakeReverseIndexSequence = typedef impl::ReverseIndexSequence<N-1, std::make_index_sequence<N> >
ReverseIndexSequence
template<std::size_t ... Is> using cie::ct::ReverseIndexSequence = typedef IndexSequence<Is...>
StaticArray
template<class TValue , Size ArraySize> using cie::StaticArray = typedef STLContainerBase<std::array<TValue,ArraySize> >
TextSerializer
using cie::io::TextSerializer = typedef Serializer<tags::Text>
Function Documentation
base10()
template<Size NDigits, concepts::Integer NT> constexpr NT cie::utils::base10 (const StaticArray< NT, NDigits > & base_N, NT base) constexpr
baseN() [1/2]
template<Size NDigits, concepts::Integer NT> constexpr StaticArray< NT, NDigits > cie::utils::baseN (NT base10, NT base) constexpr
baseN() [2/2]
template<Size NDigits, concepts::Integer NT> constexpr void cie::utils::baseN (NT base10, NT base, StaticArray< NT, NDigits > & output) constexpr
evaluatePolynomialHorner()
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd> TValue cie::utils::evaluatePolynomialHorner (TValue argument, const TItBegin it_begin, TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
Template Parameters
TValue value type of the argument and the result.
TItBegin coefficient iterator type.
TItEnd coefficient iterator type.
Parameters
argument position at which to evaluate the polynomial.
it_begin iterator pointing to the coefficient of the lowest power (0).
it_end iterator past the last coefficient.
Note
The coefficients are expected to be sorted with respect to their order in the polynomial (increasing order, starting with order 0 and including null value coefficients).
Warning
This function does not check for overflows.
This scheme can become inaccurate outside the [-1,1] argument range. Use evaluatePolynomialHornerStabilized in these cases instead.
evaluatePolynomialHornerCompound()
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd> TValue cie::utils::evaluatePolynomialHornerCompound (TValue argument, TItBegin it_begin, TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
Template Parameters
TValue value type of the argument and the result.
TItBegin coefficient iterator type.
TItEnd coefficient iterator type.
Parameters
argument position at which to evaluate the polynomial.
it_begin iterator pointing to the coefficient of the lowest power (0).
it_end iterator past the last coefficient.
Note
The coefficients are expected to be sorted with respect to their order in the polynomial (increasing order, starting with order 0 and including null value coefficients).
This scheme has a lower performance outside the [-1,1] argument range. Use evaluatePolynomialHorner if your arguments are normalized to the [-1,1] range.
Warning
This function does not check for overflows.
evaluatePolynomialHornerStabilized()
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd> TValue cie::utils::evaluatePolynomialHornerStabilized (TValue argument, TItBegin it_begin, const TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
Template Parameters
TValue value type of the argument and the result.
TItBegin coefficient iterator type.
TItEnd coefficient iterator type.
Parameters
argument position at which to evaluate the polynomial.
it_begin iterator pointing to the coefficient of the lowest power (0).
it_end iterator past the last coefficient.
Note
The coefficients are expected to be sorted with respect to their order in the polynomial (increasing order, starting with order 0 and including null value coefficients).
This scheme sacrifices some performance for accuracy outside the [-1,1] argument range. Use evaluatePolynomialHorner if your arguments are normalized to the [-1,1] range.
Warning
This function does not check for overflows.
This function computes the inverse of argument but cuts off the operation is below machine epsilon, returning 0.
evaluatePolynomialNaive()
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd> TValue cie::utils::evaluatePolynomialNaive (TValue argument, TItBegin it_begin, const TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
Template Parameters
TValue value type of the argument and the result.
TItBegin coefficient iterator type.
TItEnd coefficient iterator type.
Parameters
argument position at which to evaluate the polynomial.
it_begin iterator pointing to the coefficient of the lowest power (0).
it_end iterator past the last coefficient.
Note
The coefficients are expected to be sorted with respect to their order in the polynomial (increasing order, starting with order 0 and including null value coefficients).
Warning
This function does not check for overflows.
This scheme is prone to excessive numerical errors for higher order terms or large arguments.
exceptionFactory() [1/2]
template<concepts::STLException TException> TException cie::exceptionFactory (const String & r_location, const String & r_message, const String & r_name) noexcept
exceptionFactory() [2/2]
template<concepts::STLException TException> TException cie::exceptionFactory (TException & r_exception, const String & r_location, const String & r_additionalMessage) noexcept
flipBit()
template<concepts::Integer TInteger, concepts::Integer TIndex = Size> TInteger cie::utils::flipBit (TInteger integer, TIndex bitIndex)
getBit()
template<concepts::Integer TInteger, concepts::Integer TIndex = Size> bool cie::utils::getBit (TInteger integer, TIndex bitIndex)
getMSBIndex()
template<concepts::UnsignedInteger TInteger> constexpr std::uint8_t cie::utils::getMSBIndex (TInteger integer) constexpr noexcept
Get the index of the most significat set bit (counting from LSB)
Note
Returns 0 if the input is 0.
getNumberOfTrailingZeros()
template<concepts::UnsignedInteger TInteger> std::uint8_t cie::utils::getNumberOfTrailingZeros (TInteger integer) noexcept
Find the number of trailing zeros of the input integer's binary representation.
Todo:
Add compiler-specifics.
getRef() [1/2]
template<class T > requires concepts::Pointer<T> const std::pointer_traits< typenamestd::decay< T >::type >::element_type & cie::utils::getRef (const T & r_p) inline
References CIE_CHECK_POINTER.
getRef() [2/2]
template<class T > requires concepts::Pointer<T> std::pointer_traits< typenamestd::decay< T >::type >::element_type & cie::utils::getRef (T & r_p) inline
References CIE_CHECK_POINTER.
getThreadIDs()
const std::unordered_set< std::thread::id > & cie::mp::getThreadIDs ()
intPow()
template<concepts::Integer BaseType, concepts::Integer ExponentType> constexpr BaseType cie::intPow (BaseType base, ExponentType exponent) constexpr
make_shared_from_tuple()
template<class T , class ... Args> std::shared_ptr< T > cie::utils::make_shared_from_tuple (std::tuple< Args... > & args)
makeInternalStateIterator()
template<concepts::Container ContainerType> InternalStateIterator< const ContainerType > cie::utils::makeInternalStateIterator (const ContainerType & container, Size size)
Create a state iterator structure with 'size' components that has |container.size()|^size number of states. This basically creates an iterator through all possible combinations of the container values.
makeStateIterator() [1/2]
template<concepts::Container ContainerType> requires concepts::Container<typename ContainerType::value_type> StateIterator< typename ContainerType::const_iterator > cie::utils::makeStateIterator (const ContainerType & container)
makeStateIterator() [2/2]
template<class IteratorType > requires concepts::Container<typename std::iterator_traits<IteratorType>::value_type> StateIterator< IteratorType > cie::utils::makeStateIterator (IteratorType begin, IteratorType end)
makeTransformIterator()
template<class TIterator , class TFunction > auto cie::utils::makeTransformIterator (TIterator it, const TFunction * p_function)
makeTransformView()
template<class OutputType , class ContainerType > TransformView< ContainerType, OutputType > cie::utils::makeTransformView (const ContainerType & r_container, typename TransformView< ContainerType, OutputType >::transform_type transformFunctor)
operator<<()
std::ostream & cie::io::operator<< (std::ostream & r_stream, const JSONObject & r_json)
reinterpretBase()
template<Size NDigits, concepts::Integer NT> constexpr NT cie::utils::reinterpretBase (const StaticArray< NT, NDigits > & base_N, NT newBase) constexpr
reserve()
template<concepts::ReservableContainer ContainerType> void cie::utils::reserve (ContainerType & container, Size size) inline
References cie::STLContainerBase< TBase >::reserve().
Referenced by cie::STLContainerBase< TBase >::STLContainerBase().
resize()
template<concepts::ResizableContainer ContainerType> void cie::utils::resize (ContainerType & container, Size size) inline
References cie::STLContainerBase< TBase >::resize().
Referenced by cie::STLContainerBase< TBase >::STLContainerBase().
zip() [1/2]
template<detail::Zippables ... TContainers> detail::ZipObject< TContainers... > cie::utils::zip (Size size, TContainers &&... r_containers)
zip() [2/2]
template<detail::Zippables ... TContainers> detail::ZipObject< TContainers... > cie::utils::zip (TContainers &&... r_containers)
Variable Documentation
Empty
template<class ... Ts> constexpr bool cie::ct::Empty = PackSize<Ts...> == 0 inline constexpr
IsUnique
template<class ... TArgs> constexpr const bool cie::ct::IsUnique = detail::IsUnique<std::tuple<TArgs...>>::isUnique() inline constexpr
True if the provided parameter pack has no duplicate types.
Note
The parameter pack must not contain void.
O^2 implementation :'(
PackSize
template<class ... Ts> constexpr Size cie::ct::PackSize = sizeof...(Ts) inline constexpr