cieutils: modules.benchutils.graphics Namespace Reference
modules.benchutils.graphics Namespace Reference
Functions
def findMinPrefix (list[Result] contents, str quantityName)
None homogenizeUnits (Result results, str quantityName, str commonPrefix="")
typing.Any plotQuantity (Result results, str quantityName, pyplot.Axes axes, list[float] color=colors["TUMBlue"], list[float] textColor=colors["black"], str prefix=None, str label="", numpy.array positions=None, int barCount=1, int barIndex=0, float totalWidth=0.8, format=R"{:.2E}")
None plot (list[Result] contents, list[str] quantityNames=None, tuple[int, int] labelSizes=(16, 16), tuple[list[float], list[float]] labelColors=(colors["black"], colors["black"]))
Variables
dictionary colors
Function Documentation
findMinPrefix()
def modules.benchutils.graphics.findMinPrefix (list[Result] contents, str quantityName)
Referenced by modules.benchutils.graphics.homogenizeUnits(), and modules.benchutils.graphics.plotQuantity().
homogenizeUnits()
None modules.benchutils.graphics.homogenizeUnits (Result results, str quantityName, str commonPrefix = "")
References modules.benchutils.graphics.findMinPrefix().
Referenced by modules.benchutils.graphics.plotQuantity().
plot()
None modules.benchutils.graphics.plot (list[Result] contents, list[str] quantityNames = None, tuple[int,int] labelSizes = (16, 16), tuple[list[float],list[float]] labelColors = (colors["black"], colors["black"]))
References modules.benchutils.graphics.plotQuantity(), and cie::utils.zip().
plotQuantity()
typing.Any modules.benchutils.graphics.plotQuantity (Result results, str quantityName, pyplot.Axes axes, list[float] color = colors["TUMBlue"], list[float] textColor = colors["black"], str prefix = None, str label = "", numpy.array positions = None, int barCount = 1, int barIndex = 0, float totalWidth = 0.8, format = R"{:.2E}")
References modules.benchutils.graphics.findMinPrefix(), and modules.benchutils.graphics.homogenizeUnits().
Referenced by modules.benchutils.graphics.plot().
Variable Documentation
colors
dictionary modules.benchutils.graphics.colors
Initial value:
 =  {
     "TUMBlue" : [v / 255.0 for v in (0, 82, 147, 0xff)],
     "TUMOrange" : [v / 255.0 for v in (227, 114, 34, 0xff)],
     "warning" : [v / 255.0 for v in (0xff, 0xcc, 0xcc, 0xff)],
     "black" : [0.0, 0.0, 0.0, 1.0],
     "gray" : [0.5, 0.5, 0.5, 1.0]
 }