cieutils: cie::utils Namespace Reference
cie::utils Namespace Reference
Namespaces
observer
Classes
class ArgParse
class LogBlock
class Loggee
class Logger
class LoggerSingleton
class Profiler
class ProfilerSingleton
class FloatComparison
class Comparison
class Comparison< TFloat >
class NChooseK
class FileManager
class TransformIterator
class TransformView
struct Hash
struct Equal
struct Hash< std::pair< TFirst, TSecond > >
struct Equal< std::pair< TFirst, TSecond > >
class MarchingContainer
class NoOpIterator
class RuntimeConst
class StateIterator
class InternalStateIterator
class StrongTypeDef
class StrongTypeDef< T, Tag >
struct SymmetricPair
Identical to std::pair but overloads comparison and hash operators to disregard member order.
struct Hash< SymmetricPair< TValue > >
class ConstructorTracker
class AbsTree
class ContiguousTree
class IDObject
class NamedObject
Typedefs
using LoggerPtr = std::shared_ptr< Logger >
Functions
OutputStream & operator<< (OutputStream &r_stream, const ArgParse::Results &r_parsedArguments)
std::ostream & operator<< (std::ostream &r_stream, const ArgParse::Results &r_parsedArguments)
LogBlock & operator<< (LogBlock &r_block, const std::string &r_message)
template<Size NDigits, concepts::Integer NT>
constexpr void baseN (NT base10, NT base, StaticArray< NT, NDigits > &output)
template<Size NDigits, concepts::Integer NT>
constexpr StaticArray< NT, NDigits > baseN (NT base10, NT base)
template<Size NDigits, concepts::Integer NT>
constexpr NT base10 (const StaticArray< NT, NDigits > &base_N, NT base)
template<Size NDigits, concepts::Integer NT>
constexpr NT reinterpretBase (const StaticArray< NT, NDigits > &base_N, NT newBase)
template<concepts::Integer TInteger, concepts::Integer TIndex = Size>
TInteger flipBit (TInteger integer, TIndex bitIndex)
template<concepts::Integer TInteger, concepts::Integer TIndex = Size>
bool getBit (TInteger integer, TIndex bitIndex)
template<concepts::UnsignedInteger TInteger>
std::uint8_t getMSBIndex (TInteger integer) noexcept
template<concepts::UnsignedInteger TInteger>
std::uint8_t getNumberOfTrailingZeros (TInteger integer) noexcept
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd>
TValue evaluatePolynomialNaive (TValue argument, TItBegin it_begin, const TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd>
TValue evaluatePolynomialHorner (TValue argument, const TItBegin it_begin, TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd>
TValue evaluatePolynomialHornerStabilized (TValue argument, TItBegin it_begin, const TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
template<concepts::Numeric TValue, concepts::WeakIterator< TValue > TItBegin, concepts::WeakIterator< TValue > TItEnd>
TValue evaluatePolynomialHornerCompound (TValue argument, TItBegin it_begin, TItEnd it_end) noexcept
Evaluate a polynomial as it is written in its canonical form.
template<class TIterator , class TFunction >
auto makeTransformIterator (TIterator it, const TFunction *p_function)
template<class OutputType , class ContainerType >
TransformView< ContainerType, OutputType > makeTransformView (const ContainerType &r_container, typename TransformView< ContainerType, OutputType >::transform_type transformFunctor)
template<class TValue , class TContainer = DynamicArray<TValue*>>
requires (concepts::Container< TContainer, const TValue * >||concepts::Container< TContainer, TValue * >) class UnstructuredView
A container that stores pointers to items but provides access through references.
template<class T >
requires concepts::Pointer< T > std::pointer_traits< typename std::decay< T >::type >::element_type & getRef (T &r_p)
template<class T >
requires concepts::Pointer< T > const std::pointer_traits< typename std::decay< T >::type >::element_type & getRef (const T &r_p)
template<class T >
requires concepts::NonPointer< T > T & getRef (T &r)
template<class T >
requires concepts::NonPointer< T > const T & getRef (const T &r)
template<class T , class ... Args>
std::shared_ptr< T > make_shared_from_tuple (std::tuple< Args... > &args)
template<class T >
NoOpIterator< T > makeNoOpIterator (T it)
template<concepts::ResizableContainer ContainerType>
void resize (ContainerType &container, Size size)
template<concepts::ReservableContainer ContainerType>
void reserve (ContainerType &container, Size size)
template<concepts::Container ContainerType>
StateIterator< typename ContainerType::const_iterator > makeStateIterator(const ContainerType &container) requires concepts InternalStateIterator< const ContainerType > makeInternalStateIterator (const ContainerType &container, Size size)
template<class T , class Tag >
bool operator== (const StrongTypeDef< T, Tag > &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class T , class Tag >
bool operator== (const StrongTypeDef< T, Tag > &r_lhs, const T &r_rhs) noexcept
template<class T , class Tag >
bool operator== (const T &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class T , class Tag >
bool operator!= (const StrongTypeDef< T, Tag > &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class T , class Tag >
bool operator!= (const StrongTypeDef< T, Tag > &r_lhs, const T &r_rhs) noexcept
template<class T , class Tag >
bool operator!= (const T &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class T , class Tag >
bool operator< (const StrongTypeDef< T, Tag > &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class T , class Tag >
bool operator< (const StrongTypeDef< T, Tag > &r_lhs, const T &r_rhs) noexcept
template<class T , class Tag >
bool operator< (const T &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class T , class Tag >
bool operator> (const StrongTypeDef< T, Tag > &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class T , class Tag >
bool operator> (const StrongTypeDef< T, Tag > &r_lhs, const T &r_rhs) noexcept
template<class T , class Tag >
bool operator> (const T &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class T , class Tag >
bool operator<= (const StrongTypeDef< T, Tag > &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class T , class Tag >
bool operator<= (const StrongTypeDef< T, Tag > &r_lhs, const T &r_rhs) noexcept
template<class T , class Tag >
bool operator<= (const T &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class T , class Tag >
bool operator>= (const StrongTypeDef< T, Tag > &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class T , class Tag >
bool operator>= (const StrongTypeDef< T, Tag > &r_lhs, const T &r_rhs) noexcept
template<class T , class Tag >
bool operator>= (const T &r_lhs, const StrongTypeDef< T, Tag > &r_rhs) noexcept
template<class TValue >
bool operator== (Ref< const SymmetricPair< TValue >> r_lhs, Ref< const SymmetricPair< TValue >> r_rhs) noexcept
template<class TValue >
bool operator!= (Ref< const SymmetricPair< TValue >> r_lhs, Ref< const SymmetricPair< TValue >> r_rhs) noexcept
template<detail::Zippables ... TContainers>
detail::ZipObject< TContainers... > zip (Size size, TContainers &&... r_containers)
template<detail::Zippables ... TContainers>
detail::ZipObject< TContainers... > zip (TContainers &&... r_containers)
Typedef Documentation
LoggerPtr
using cie::utils::LoggerPtr = typedef std::shared_ptr<Logger>
Function Documentation
base10()
template<Size NDigits, concepts::Integer NT> constexpr NT cie::utils::base10 (const StaticArray< NT, NDigits > & base_N, NT base) constexpr
baseN() [1/2]
template<Size NDigits, concepts::Integer NT> constexpr StaticArray<NT,NDigits> cie::utils::baseN (NT base10, NT base) constexpr
baseN() [2/2]
template<Size NDigits, concepts::Integer NT> constexpr void cie::utils::baseN (NT base10, NT base, StaticArray< NT, NDigits > & output) constexpr
flipBit()
template<concepts::Integer TInteger, concepts::Integer TIndex = Size> TInteger cie::utils::flipBit (TInteger integer, TIndex bitIndex)
getBit()
template<concepts::Integer TInteger, concepts::Integer TIndex = Size> bool cie::utils::getBit (TInteger integer, TIndex bitIndex)
getMSBIndex()
template<concepts::UnsignedInteger TInteger> std::uint8_t cie::utils::getMSBIndex (TInteger integer) noexcept
getNumberOfTrailingZeros()
template<concepts::UnsignedInteger TInteger> std::uint8_t cie::utils::getNumberOfTrailingZeros (TInteger integer) noexcept
getRef() [1/4]
template<class T > requires concepts::NonPointer<T> const T& cie::utils::getRef (const T & r) inline
getRef() [2/4]
template<class T > requires concepts::Pointer<T> const std::pointer_traits<typename std::decay<T>::type>::element_type& cie::utils::getRef (const T & r_p) inline
References CIE_CHECK_POINTER.
getRef() [3/4]
template<class T > requires concepts::NonPointer<T> T& cie::utils::getRef (T & r) inline
getRef() [4/4]
template<class T > requires concepts::Pointer<T> std::pointer_traits<typename std::decay<T>::type>::element_type& cie::utils::getRef (T & r_p) inline
References CIE_CHECK_POINTER.
make_shared_from_tuple()
template<class T , class ... Args> std::shared_ptr<T> cie::utils::make_shared_from_tuple (std::tuple< Args... > & args)
makeNoOpIterator()
template<class T > NoOpIterator<T> cie::utils::makeNoOpIterator (T it)
makeTransformView()
template<class OutputType , class ContainerType > TransformView<ContainerType,OutputType> cie::utils::makeTransformView (const ContainerType & r_container, typename TransformView< ContainerType, OutputType >::transform_type transformFunctor)
operator!=() [1/4]
template<class T , class Tag > bool cie::utils::operator!= (const StrongTypeDef< T, Tag > & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
Referenced by requires().
operator!=() [2/4]
template<class T , class Tag > bool cie::utils::operator!= (const StrongTypeDef< T, Tag > & r_lhs, const T & r_rhs) noexcept
operator!=() [3/4]
template<class T , class Tag > bool cie::utils::operator!= (const T & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
operator!=() [4/4]
template<class TValue > bool cie::utils::operator!= (Ref< const SymmetricPair< TValue >> r_lhs, Ref< const SymmetricPair< TValue >> r_rhs) noexcept
operator<() [1/3]
template<class T , class Tag > bool cie::utils::operator< (const StrongTypeDef< T, Tag > & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
Referenced by requires().
operator<() [2/3]
template<class T , class Tag > bool cie::utils::operator< (const StrongTypeDef< T, Tag > & r_lhs, const T & r_rhs) noexcept
operator<() [3/3]
template<class T , class Tag > bool cie::utils::operator< (const T & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
operator<<() [1/3]
LogBlock& cie::utils::operator<< (LogBlock & r_block, const std::string & r_message)
operator<<() [2/3]
OutputStream& cie::utils::operator<< (OutputStream & r_stream, const ArgParse::Results & r_parsedArguments)
operator<<() [3/3]
std::ostream& cie::utils::operator<< (std::ostream & r_stream, const ArgParse::Results & r_parsedArguments)
operator<=() [1/3]
template<class T , class Tag > bool cie::utils::operator<= (const StrongTypeDef< T, Tag > & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
operator<=() [2/3]
template<class T , class Tag > bool cie::utils::operator<= (const StrongTypeDef< T, Tag > & r_lhs, const T & r_rhs) noexcept
operator<=() [3/3]
template<class T , class Tag > bool cie::utils::operator<= (const T & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
operator==() [1/4]
template<class T , class Tag > bool cie::utils::operator== (const StrongTypeDef< T, Tag > & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
operator==() [2/4]
template<class T , class Tag > bool cie::utils::operator== (const StrongTypeDef< T, Tag > & r_lhs, const T & r_rhs) noexcept
operator==() [3/4]
template<class T , class Tag > bool cie::utils::operator== (const T & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
operator==() [4/4]
template<class TValue > bool cie::utils::operator== (Ref< const SymmetricPair< TValue >> r_lhs, Ref< const SymmetricPair< TValue >> r_rhs) noexcept
operator>() [1/3]
template<class T , class Tag > bool cie::utils::operator> (const StrongTypeDef< T, Tag > & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
operator>() [2/3]
template<class T , class Tag > bool cie::utils::operator> (const StrongTypeDef< T, Tag > & r_lhs, const T & r_rhs) noexcept
operator>() [3/3]
template<class T , class Tag > bool cie::utils::operator> (const T & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
operator>=() [1/3]
template<class T , class Tag > bool cie::utils::operator>= (const StrongTypeDef< T, Tag > & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
operator>=() [2/3]
template<class T , class Tag > bool cie::utils::operator>= (const StrongTypeDef< T, Tag > & r_lhs, const T & r_rhs) noexcept
operator>=() [3/3]
template<class T , class Tag > bool cie::utils::operator>= (const T & r_lhs, const StrongTypeDef< T, Tag > & r_rhs) noexcept
reinterpretBase()
template<Size NDigits, concepts::Integer NT> constexpr NT cie::utils::reinterpretBase (const StaticArray< NT, NDigits > & base_N, NT newBase) constexpr
reserve()
template<concepts::ReservableContainer ContainerType> void cie::utils::reserve (ContainerType & container, Size size) inline
Referenced by requires(), and cie::STLContainerBase< TBase >::STLContainerBase().
resize()
template<concepts::ResizableContainer ContainerType> void cie::utils::resize (ContainerType & container, Size size) inline
zip() [1/2]
template<detail::Zippables ... TContainers> detail::ZipObject<TContainers...> cie::utils::zip (Size size, TContainers &&... r_containers)
Referenced by modules.benchutils.graphics::plot().
zip() [2/2]
template<detail::Zippables ... TContainers> detail::ZipObject<TContainers...> cie::utils::zip (TContainers &&... r_containers)